
// -*- C++ -*-
// $Id: Version.h 87810 2009-11-29 19:06:18Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.

#define ACE_MAJOR_VERSION 5
#define ACE_MINOR_VERSION 7
#define ACE_BETA_VERSION 5
#define ACE_VERSION "5.7.5"
